### ISSUE TITLE
traefik ssl issues

### ISSUE THREAD

**Issue by satyajitghana** [fluential/ant-media-server-docker#4]
Is there an update to this? I've tried `docker-compose.traefik.yml` and it doesn't seem to work with https

`docker compose -f docker-compose.traefik.yml up`

I've tried `http://192.168.0.122:5080/WebRTCApp/index.html`, with port `5080`, `5443`, `443` and neither of them seems to be https.

**Comment by fluential** [comment]
You need to edit config file with your custom domain for which certificate should be issued.

**Comment by satyajitghana** [comment]
@fluential yes ! I messed that up, I realised that.

but I need to test it on local network with local ip, not localhost, any help on how this would be done? I couldn't get it to work still.

do I have to use something like ngrok ?

**Comment by fluential** [comment]
Just use default docker compose file, not traefik.

**Comment by satyajitghana** [comment]
so it seems this is not a docker issue thing?

because i still can't access https://192.168.0.122:5443/ BUT http://192.168.0.122:5080/ is accessible 

i'm using the normal docker compose file now, with just `docker-compose up`

**Comment by satyajitghana** [comment]
i tried this now: https://github.com/ant-media/Ant-Media-Server/wiki/Frequently-Asked-Questions#how-to-use-self-signed-certificate-on-ant-media-server and it works !
